import { useRef } from 'react'
import { useGSAP } from '@gsap/react'
import gsap from 'gsap'
import { ScrollTrigger } from 'gsap/ScrollTrigger'
import { Canvas, useFrame } from '@react-three/fiber'
import * as THREE from 'three'
import { Factory, Users, ScanLine, CloudRain, Recycle, FileCheck, LucideIcon } from 'lucide-react'

gsap.registerPlugin(ScrollTrigger)

interface MetricDef {
    icon: LucideIcon
    index: string
    number: string
    suffix: string
    label: string
    desc: string
}

const metrics: MetricDef[] = [
    { icon: Factory, index: '01', number: '6', suffix: '', label: 'Industries Covered', desc: 'Automotive, HVAC, Steel, Plastic, Aluminium & Battery — all within one unified platform.' },
    { icon: Users, index: '02', number: '25', suffix: '', label: 'Stakeholders Onboarded', desc: 'Active organizations operating across the global value chain, all connected in real time.' },
    { icon: ScanLine, index: '03', number: '1,20,000', suffix: ' Tons', label: 'Tracking & Traceability', desc: 'Tonnes of material tracked end-to-end with full provenance and timestamped audit trails.' },
    { icon: CloudRain, index: '04', number: '3,56,760', suffix: ' Tons', label: 'Verified Emissions', desc: 'Tonnes of GHG measured, validated, and verified by our precision carbon intelligence layer.' },
    { icon: Recycle, index: '05', number: '73', suffix: '%', label: 'Circularity Index', desc: 'Average circularity score across tracked material flows, above industry median by 2.3×.' },
    { icon: FileCheck, index: '06', number: '15,000', suffix: '+', label: 'Automated Compliance', desc: 'Regulatory reports auto-generated by AI for CBAM, EPR, IRA and global ESG frameworks.' },
]

const topMetrics = metrics.slice(0, 3)
const bottomMetrics = metrics.slice(3, 6)

/* ─── Card: fills exactly 1/3 of the viewport ─────────────── */
const MetricNode = ({ metric }: { metric: MetricDef }) => {
    const Icon = metric.icon
    return (
        <div
            className="feature-card w-[350px] shrink-0 flex flex-col justify-between py-8 px-8 border-l border-data-navy/5 group hover:bg-neutral-50/80 transition-colors duration-500 relative"
        >
            <div className="absolute left-0 top-0 w-[3px] h-full bg-electric-sulfur scale-y-0 group-hover:scale-y-100 transition-transform duration-500 origin-top" />
            <div>
                <span className="text-[2rem] font-black text-electric-sulfur/50 leading-none block mb-2 tracking-tighter select-none pointer-events-none">{metric.index}</span>
                <div className="w-10 h-10 rounded-full bg-data-navy/5 flex items-center justify-center mb-5 group-hover:bg-electric-sulfur group-hover:text-data-navy transition-colors duration-500">
                    <Icon className="w-5 h-5 stroke-[1.5]" />
                </div>
                <p className="text-[2.4rem] font-black tracking-tighter text-electric-sulfur leading-none mb-1">
                    {metric.number}<span className="text-xl">{metric.suffix}</span>
                </p>
                <h3 className="text-[11px] font-black uppercase tracking-tighter leading-tight mb-3 group-hover:translate-x-1 transition-transform duration-500">{metric.label}</h3>
                <p className="text-[10px] font-mono uppercase leading-relaxed opacity-40 group-hover:opacity-70 transition-opacity duration-500 max-w-[280px]">{metric.desc}</p>
            </div>
        </div>
    )
}

/* ─── Rotating Wireframe Globe ─────────────────────── */
const RotatingGlobe = () => {
    const meshRef = useRef<THREE.LineSegments>(null)

    // Rotate counter-clockwise (positive Y axis rotation in Three.js)
    useFrame((_state, delta) => {
        if (meshRef.current) {
            meshRef.current.rotation.y += delta * 0.15
            meshRef.current.rotation.x = 0.2 // slight tilt
        }
    })

    return (
        <lineSegments ref={meshRef as any} position={[0, -0.24, 1]} scale={0.60}>
            <edgesGeometry attach="geometry" args={[new THREE.SphereGeometry(2.5, 32, 16)]} />
            <lineBasicMaterial attach="material" color="#96CC39" opacity={1} transparent={true} />
        </lineSegments>
    )
}

/* ─── Main component ──────────────────────────────────────── */
export const TractionNarrative = () => {
    const sectionRef = useRef<HTMLDivElement>(null)
    const contentWrapperRef = useRef<HTMLDivElement>(null)
    const topTrackRef = useRef<HTMLDivElement>(null)
    const bottomTrackRef = useRef<HTMLDivElement>(null)

    useGSAP(() => {
        if (!topTrackRef.current || !bottomTrackRef.current || !contentWrapperRef.current || !sectionRef.current) return

        const getTrackWidth = () => topTrackRef.current!.scrollWidth
        const getWindowWidth = () => window.innerWidth

        // Cards start off-screen right; rest is immediately visible
        gsap.set([topTrackRef.current, bottomTrackRef.current], { x: () => getWindowWidth() })

        const tl = gsap.timeline({
            scrollTrigger: {
                trigger: sectionRef.current,
                pin: true,
                scrub: 1,
                invalidateOnRefresh: true,
                start: 'top top',
                end: () => `+=${getTrackWidth() + getWindowWidth()}`,
            }
        })

        // Phase 1: cards scroll in from right
        tl.to([topTrackRef.current, bottomTrackRef.current], {
            x: () => getWindowWidth() - getTrackWidth(),
            ease: 'none',
            duration: () => getTrackWidth(),
        })
        // Phase 2: whole wrapper slides out left
        tl.to(contentWrapperRef.current, {
            x: () => -getWindowWidth(),
            ease: 'none',
            duration: () => getWindowWidth(),
        })

    }, { scope: sectionRef })

    return (
        <section ref={sectionRef} id="traction" className="relative w-full overflow-hidden z-[50] h-screen bg-white flex flex-col">
            <div ref={contentWrapperRef} className="relative w-full h-full flex flex-col justify-between flex-1 pt-28 pb-8">

                {/* Top row: 3 cards × 100vw/3 = full screen width */}
                <div ref={topTrackRef} className="flex items-stretch gap-0 w-max relative z-10 shrink-0 border-y border-data-navy/5 h-[30vh] max-h-[280px]">
                    {topMetrics.map(m => <MetricNode key={m.label} metric={m} />)}
                </div>

                {/* 
                    Globe Container:
                    - ON TOP of cards (z-20) but strictly pointer-events-none so hover works.
                    - Height increased to 75vh to prevent any vertical clipping.
                    - overflow-hidden removed vertically to ensure poles are visible.
                    - Right-aligned so it cuts off precisely at the section boundary.
                */}
                <div className="absolute right-0 w-[50vw] max-w-[900px] top-[12.5vh] h-[75vh] z-20 pointer-events-none fade-in opacity-100">
                    <Canvas camera={{ position: [0, 0, 6], fov: 45 }} className="w-full h-full" style={{ pointerEvents: 'none' }}>
                        <RotatingGlobe />
                    </Canvas>
                </div>

                {/* Central text */}
                <div className="relative flex-1 flex flex-col justify-center px-10 md:px-20 pointer-events-none z-10 overflow-hidden">
                    <div className="relative pointer-events-auto z-10">
                        <span className="text-electric-sulfur text-[11px] font-mono uppercase tracking-[0.4em] font-bold block mb-4">Live Telemetry</span>
                        <h2 className="text-[7vw] md:text-[5vw] font-black uppercase tracking-tighter leading-[0.85] text-data-navy max-w-3xl mb-4">
                            Real Time<br />Numbers.
                        </h2>
                        <p className="text-[11px] font-mono uppercase tracking-wider opacity-40 leading-loose max-w-lg">
                            Scroll to explore all 6 live metrics →
                        </p>

                        {/* The '6' text was here, but has been replaced by the globe. */}
                    </div>
                </div>

                {/* Bottom row */}
                <div ref={bottomTrackRef} className="flex items-stretch gap-0 w-max relative z-10 shrink-0 border-y border-data-navy/5 h-[30vh] max-h-[280px]">
                    {bottomMetrics.map(m => <MetricNode key={m.label} metric={m} />)}
                </div>

            </div>
        </section>
    )
}
